meta_product_name: “Hero”

meta_title: “Hero – Be a hero to your child”

meta_description: “Discover the best activities for your children in London. Get recommendations based on what you like. You'll never be at a loss to entertain your kids again!”

meta_image: “cover.png”
